### ISSUE TITLE
Запрошенный доступ к реестру запрещен.

### ISSUE THREAD

**Issue by Worksterq** [ThePCDuke/WinCry#1]
Прикрепил лог. Windows 8.1, Defender отключен, других манипуляций не производилось.
[log.txt](https://github.com/ThePCDuke/WinCry/files/8350572/log.txt)

**Comment by authorless** [comment]
Как вариант вам нужно запустить программу от имени администратора т.к программа пытается применить изменения в реестре вашей Windows

**Comment by Worksterq** [comment]
> Как вариант вам нужно запустить программу от имени администратора т.к программа пытается применить изменения в реестре вашей Windows

не помогло.
