### ISSUE TITLE
Диспетчер задач долго закрывается

### ISSUE THREAD

**Issue by megoRU** [ThePCDuke/WinCry#12]
![image](https://user-images.githubusercontent.com/23276305/205318759-3b1374b1-203c-425c-b193-e73047458654.png)

Пресеты и т.д: [WinCry.zip](https://github.com/ThePCDuke/WinCry/files/10141978/WinCry.zip)

**Comment by ThePCDuke** [comment]
Здравствуйте, проблема актуальна?
