### ISSUE TITLE
не работает майкрософт авторизация в играх/аппах

### ISSUE THREAD

**Issue by mrksbgg** [ThePCDuke/WinCry#18]
скорее всего, это связано с данной утилитой, ибо до этого всё было норм
запись проблемы: https://youtu.be/7gQRczTDN8M

майнкрафт даёт код ошибки "Утопленник",
 на сайте пишет для решения закройте майн, перезагрузите девайс и попробуйте снова, но ничего xd

**Comment by ThePCDuke** [comment]
Какой пресет использовали в программе?

**Comment by mrksbgg** [comment]
> Какой пресет использовали в программе?

базовый

**Comment by ThePCDuke** [comment]
При этом вход в Магазин Windows есть? Есть еще какое-либо приложение в котором не работает вход в учетку майков? В идеале бесплатное

**Comment by ThePCDuke** [comment]
Проверил на чистой 10, использовав лишь базовый профиль в WinCry, вход в учетку майкрософт в майнкрайте с магазина Windows работает

**Comment by mrksbgg** [comment]
Хм, странно, после винкрая все сломалось. я винду снёс бтв :)

**Comment by mrksbgg** [comment]
> Хм, странно, после винкрая все сломалось. я винду снёс бтв :)

не всё, а авторизация в играх
