### ISSUE TITLE
Не работает VPN WireGuard

### ISSUE THREAD

**Issue by Bed1ah** [ThePCDuke/WinCry#19]
После выставления пресета для служб "опасный" перестал работать VPN WireGuard, выводит (unable to enable firewall rules)
Выполнил бэкап, но все равно выбивает эту ошибку.

UPD: удалось исправить, для начала нужно восстановить и включить службу базовой фильтрации (BFE), если выходит ошибка: https://support.kaspersky.ru/common/error/installation/11099#error5
После этого восстанавливаем и включаем службу Dnscache и перезагружаемся.

**Comment by ThePCDuke** [comment]
Здравствуйте, при написании в поиске служб vpn, выдало бы нужные службы для фукнционала VPN)
