### ISSUE TITLE
Сетевые диски

### ISSUE THREAD

**Issue by ForestLive6** [ThePCDuke/WinCry#20]
Здравствуйте, подскажите пожалуйста, как найти службы с подключение сетевых дисков. После применения твиков со службами, подключение к сетевым диски не возможно, в поиске найти не могу.

**Comment by enrichmentt** [comment]
@ForestLive6 
**LanmanWorkstation** [Рабочая станция] 
Description:
Создает и поддерживает клиентские сетевые подключения к удаленным серверам по протоколу SMB. Если данная служба будет остановлена, эти подключения станут недоступными. Если данная служба отключена, все явно зависящие от нее службы запустить не удастся.
