### ISSUE TITLE
Корректировка галочек во вкладке служб в режиме "WinCry - Базовый"

### ISSUE THREAD

**Issue by authorless** [ThePCDuke/WinCry#3]
Здравствуйте. Я бы хотел попросить вас снять галочку со службы "VaultSvc" в режим "WinCry - Базовый", т.к по моим наблюдениям она убила возможность войти в учетную запись Windows при запуске Windows. Пришлось поднимать восстановление.  
Пояснение, что происходит: В общем после применения на эту службу "отключение", и последующего перезапуска системы вы не сможете войти в учетную запись Microsoft т.к не будет появляться окошко со входом. (Это скорее всего в том случае если вы при установке винды выбрали вход только через учетную запись Microsoft)

**Comment by ThePCDuke** [comment]
Здравствуйте, а подскажите на какой версии Windows 10 (Также можно указать редакцию) нашли такую проблему? И почему уверены, что проблема с "VaultSvc"?

**Comment by authorless** [comment]
Windows 10 21H2. Сборка 19044.1645. А проблема именно с этой службой т.к я все перепроверил (каждую функцию) и именно с ней у меня проблема возникла после ее отключения. Возможно это не распространяется если у вас будет локальная учетная запись

**Comment by ThePCDuke** [comment]
Как я понимаю, Вы сразу на этапе установки входите в аккаунт Майков?

**Comment by authorless** [comment]
Да, именно

**Comment by ThePCDuke** [comment]
А есть возможность скинуть образ установленной 10? Просто спустя миллион тестирований не выявил такую проблему как у Вас. Может есть возможность связаться где-нибудь в более удобном для этого места?

**Comment by authorless** [comment]
К сожалению сборка у меня обычная, но она оптимизировалась через многие программы (да, мазохизм). Возможно какая-то одна из программ оптимизаторов что-то сломала и из-за этого начались проблемы именно с этим сервисом, хотя восстановление через sfc scannow написала что все в порядке. Возможно это единичный случай тогда и проявляется непонятно из-за чего. А снова реализовать его я не представляю как, чтобы добиться моего дефекта
